"""
test_report_generator.py
------------------------
Unit tests for the Report Generator (Task 18).

Covers:
  - Generated bytes are non-empty and start with %PDF magic bytes (Req 8.1)
  - Required section headings are present in the PDF text (Req 8.4)
  - Header fields present: ISO 8601 timestamp, source URL, platform name (Req 8.3)
  - ReportGenerationError raised on empty/invalid session data (Req 8.1)

Requirements: 8.1, 8.3, 8.4
"""

import io
import re
import pytest

from app.reports.report_generator import (
    PLATFORM_NAME,
    ReportGenerationError,
    generate_report,
)

# ---------------------------------------------------------------------------
# PDF text extraction helper (uses pdfminer.six which is available in the env)
# ---------------------------------------------------------------------------

def extract_pdf_text(pdf_bytes: bytes) -> str:
    """Return all text extracted from a PDF given as raw bytes."""
    from pdfminer.high_level import extract_text

    return extract_text(io.BytesIO(pdf_bytes))


# ---------------------------------------------------------------------------
# Shared fixture: a minimal but complete session_data dict
# ---------------------------------------------------------------------------

SAMPLE_SESSION: dict = {
    "session_id": "test-session-123",
    "source_url": "https://example.com",
    "detected_patterns": [
        {
            "category": "Fake Urgency",
            "element_identifier": "countdown-timer",
            "confidence_level": "High",
            "explanation": "This element uses urgency language.",
        }
    ],
    "scores": {
        "manipulation_score": {
            "score": 75.0,
            "contributions": [{"pattern_name": "Fake Urgency", "points": 20.0}],
        },
        "trust_score": {
            "score": 25.0,
            "contributions": [{"pattern_name": "Fake Urgency", "points": 20.0}],
        },
        "friction_score": {
            "score": 0.0,
            "contributions": [],
        },
        "ux_fairness_index": "High Risk",
    },
    "simulation_results": [
        {
            "persona": "Elderly User",
            "behavioral_summary": "Elderly users may be confused.",
            "confusion_points": [],
            "pressure_points": [],
            "hidden_risk_areas": [],
            "accidental_consent_zones": [],
        }
    ],
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _generate(session: dict | None = None) -> bytes:
    """Call generate_report with SAMPLE_SESSION (or a custom dict) and return bytes."""
    return generate_report(session if session is not None else SAMPLE_SESSION)


# ===========================================================================
# 1. PDF bytes validity
# ===========================================================================

class TestPDFBytesValidity:
    """
    Req 8.1 – Report_Generator SHALL produce a PDF.
    The result must be non-empty raw bytes beginning with the %PDF magic bytes.
    """

    def test_returns_bytes_type(self):
        result = _generate()
        assert isinstance(result, bytes), "generate_report must return bytes"

    def test_bytes_are_non_empty(self):
        result = _generate()
        assert len(result) > 0, "PDF bytes must not be empty"

    def test_starts_with_pdf_magic_bytes(self):
        result = _generate()
        assert result[:4] == b"%PDF", (
            f"PDF must start with %PDF magic bytes, got {result[:4]!r}"
        )

    def test_pdf_version_header_present(self):
        """The %PDF magic bytes are followed by a version number like %PDF-1.x."""
        result = _generate()
        header = result[:8].decode("latin-1", errors="replace")
        assert header.startswith("%PDF-"), (
            f"Expected %PDF-<version> header, got {header!r}"
        )

    def test_minimum_reasonable_size(self):
        """A valid multi-section PDF should be at least a few kilobytes."""
        result = _generate()
        assert len(result) >= 4096, (
            f"PDF is suspiciously small ({len(result)} bytes); expected >= 4096"
        )


# ===========================================================================
# 2. Required section headings
# ===========================================================================

# These are the exact heading strings the report generator emits (see
# _section_heading calls in report_generator.py).
REQUIRED_SECTIONS = [
    "Executive Summary",
    "Detected Dark Patterns",
    "Risk Scores",
    "Behavioral Simulation Summaries",
    "Ethical Redesign Recommendations",
    "Annotated Screenshot",
]


class TestRequiredSectionHeadings:
    """
    Req 8.4 – PDF SHALL have clearly labeled section headings.
    Every required section must appear in the extracted PDF text.
    """

    @pytest.fixture(scope="class")
    def pdf_text(self):
        pdf_bytes = _generate()
        return extract_pdf_text(pdf_bytes)

    @pytest.mark.parametrize("heading", REQUIRED_SECTIONS)
    def test_section_heading_present(self, pdf_text, heading):
        assert heading in pdf_text, (
            f"Required section heading '{heading}' not found in PDF text.\n"
            f"Extracted text snippet: {pdf_text[:500]!r}"
        )

    def test_all_six_sections_present(self, pdf_text):
        missing = [s for s in REQUIRED_SECTIONS if s not in pdf_text]
        assert not missing, f"Missing sections in PDF: {missing}"

    def test_table_of_contents_present(self, pdf_text):
        """The PDF must include a Table of Contents section."""
        assert "Table of Contents" in pdf_text, (
            "Table of Contents heading not found in PDF text"
        )


# ===========================================================================
# 3. Header fields (Req 8.3)
# ===========================================================================

class TestHeaderFields:
    """
    Req 8.3 – Report header SHALL contain:
      (a) analysis timestamp in ISO 8601 format (e.g. 2024-01-01T00:00:00Z)
      (b) analyzed source URL or filename
      (c) platform name and version ("MIRROR X AI v1.0")
    """

    @pytest.fixture(scope="class")
    def pdf_text(self):
        return extract_pdf_text(_generate())

    # (a) ISO 8601 timestamp  – pattern: YYYY-MM-DDTHH:MM:SSZ
    def test_iso8601_timestamp_present(self, pdf_text):
        iso_pattern = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z")
        assert iso_pattern.search(pdf_text), (
            "No ISO 8601 timestamp (YYYY-MM-DDTHH:MM:SSZ) found in PDF text"
        )

    def test_timestamp_label_present(self, pdf_text):
        """The metadata table should label the field 'Timestamp (ISO 8601)'."""
        assert "Timestamp" in pdf_text or "ISO 8601" in pdf_text, (
            "Timestamp label not found in PDF text"
        )

    # (b) Analyzed source
    def test_source_url_present(self, pdf_text):
        source = SAMPLE_SESSION["source_url"]
        assert source in pdf_text, (
            f"Source URL '{source}' not found in PDF text"
        )

    def test_analyzed_source_label_present(self, pdf_text):
        assert "Analyzed Source" in pdf_text or "source" in pdf_text.lower(), (
            "Analyzed Source label not found in PDF text"
        )

    # (c) Platform name and version
    def test_platform_name_present(self, pdf_text):
        assert PLATFORM_NAME in pdf_text, (
            f"Platform name '{PLATFORM_NAME}' not found in PDF text"
        )

    def test_platform_name_is_mirror_x_ai_v1(self):
        """PLATFORM_NAME constant must be the expected string."""
        assert PLATFORM_NAME == "MIRROR X AI v1.0", (
            f"Expected PLATFORM_NAME='MIRROR X AI v1.0', got {PLATFORM_NAME!r}"
        )

    # Source filename fallback
    def test_source_filename_fallback(self):
        """When source_url is absent, source_filename should appear in the PDF."""
        session = {**SAMPLE_SESSION, "source_url": None, "source_filename": "upload.png"}
        pdf_bytes = generate_report(session)
        text = extract_pdf_text(pdf_bytes)
        assert "upload.png" in text, (
            "source_filename 'upload.png' not found in PDF text when source_url is None"
        )


# ===========================================================================
# 4. ReportGenerationError raised on invalid/empty session data
# ===========================================================================

class TestReportGenerationError:
    """
    Req 8.1 – generate_report SHALL raise ReportGenerationError on failure.
    """

    def test_error_class_exists(self):
        assert ReportGenerationError is not None

    def test_error_is_exception_subclass(self):
        assert issubclass(ReportGenerationError, Exception)

    def test_error_has_message_attribute(self):
        err = ReportGenerationError("test message")
        assert err.message == "test message"

    def test_error_has_cause_attribute(self):
        cause = ValueError("root cause")
        err = ReportGenerationError("wrapper", cause=cause)
        assert err.cause is cause

    def test_raises_on_none_input(self):
        """Passing None instead of a dict must raise ReportGenerationError."""
        with pytest.raises(ReportGenerationError):
            generate_report(None)  # type: ignore[arg-type]

    def test_raises_on_non_dict_input(self):
        """Passing a non-dict must raise ReportGenerationError."""
        with pytest.raises(ReportGenerationError):
            generate_report("not a dict")  # type: ignore[arg-type]

    def test_raises_on_integer_input(self):
        with pytest.raises(ReportGenerationError):
            generate_report(42)  # type: ignore[arg-type]

    def test_empty_dict_does_not_raise(self):
        """
        An empty dict is valid session data (all fields optional / with defaults).
        The generator must produce a PDF without raising.
        """
        result = generate_report({})
        assert isinstance(result, bytes)
        assert result[:4] == b"%PDF"

    def test_minimal_session_no_patterns_succeeds(self):
        """Session with no detected_patterns should generate a valid PDF."""
        session = {
            "session_id": "empty-patterns",
            "source_url": "https://clean.example.com",
            "detected_patterns": [],
            "scores": {
                "manipulation_score": {"score": 0.0, "contributions": []},
                "trust_score": {"score": 100.0, "contributions": []},
                "friction_score": {"score": 0.0, "contributions": []},
                "ux_fairness_index": "Fair",
            },
            "simulation_results": [],
        }
        result = generate_report(session)
        assert result[:4] == b"%PDF"


# ===========================================================================
# 5. Content smoke tests – pattern data included in report
# ===========================================================================

class TestReportContent:
    """
    Smoke tests verifying that actual session content appears in the PDF.
    Validates Req 8.1 (report includes all detected dark patterns and scores).
    """

    @pytest.fixture(scope="class")
    def pdf_text(self):
        return extract_pdf_text(_generate())

    def test_detected_pattern_category_in_pdf(self, pdf_text):
        category = SAMPLE_SESSION["detected_patterns"][0]["category"]
        assert category in pdf_text, (
            f"Pattern category '{category}' not found in PDF text"
        )

    def test_ux_fairness_index_in_pdf(self, pdf_text):
        fairness = SAMPLE_SESSION["scores"]["ux_fairness_index"]
        assert fairness in pdf_text, (
            f"UX Fairness Index value '{fairness}' not found in PDF text"
        )

    def test_persona_name_in_simulation_section(self, pdf_text):
        persona = SAMPLE_SESSION["simulation_results"][0]["persona"]
        assert persona in pdf_text, (
            f"Persona '{persona}' not found in PDF simulation section"
        )

    def test_page_numbers_present(self, pdf_text):
        """Page number footer text 'Page' must appear somewhere in the PDF."""
        assert "Page" in pdf_text, "Page number footer not found in PDF text"
